# You can install this with the experimental [`conda-env`][1] package.
#
#   conda env create -n design --file=environment.yml
#
# [1]: https://github.com/conda/conda-env/
name: conda.io
channels:
  - javascript
  - continuumio
dependencies:
  - python<=3
  - flask
  - bower
  - gulp
  - continuum-flask
  - nodejs
