# You can install this with the experimental [`conda-env`][1] package.
#
#   conda env create -n design --file=environment.yml
channels:
  - javascript
dependencies:
  - python<=3
  - flask
  - bower
  - gulp
